GET http://localhost:8080/api/rooms HTTP/1.1
###
GET http://localhost:8080/api/rooms/1 HTTP/1.1
###
POST http://localhost:8080/api/rooms HTTP/1.1
content-type: application/json

{
    "name": "New Room",
    "capacity": 100
}
###
DELETE http://localhost:8080/api/rooms/1 HTTP/1.1
###
PUT http://localhost:8080/api/rooms/2 HTTP/1.1
content-type: application/json

{
    "name": "Totally not the same"
}