GET http://localhost:8080/api/actions/organizeAtendees HTTP/1.1
###
POST http://localhost:8080/api/person/save HTTP/1.1
content-type: application/json

{
    "firstName": " sample ",
    "lastName": " personas "
}
###
GET http://localhost:8080/api/person/all HTTP/1.1
###
GET http://localhost:8080/api/person/id/1 HTTP/1.1
###
PUT http://localhost:8080/api/person/update/1 HTTP/1.1
content-type: application/json

{
    "firstName": "Will",
    "lastName": "Admin",
    "loungeRoom":{"id":1},
    "eventRoom1":{"id":1},
    "eventRoom2":{"id":2}
}
###
DELETE http://localhost:8080/api/person/delete/2 HTTP/1.1
###
